# Following variables must be specified in GitLab CI group variables set:
#   * AWS_ACCOUNTID
#   * SERVERLESS_DEPLOYMENT_BUCKET
#   * AWS_DEFAULT_REGION
#   * CI_IMAGE
#   * VAULT_ADDR

# following variables must be specified explicitly for the gitlab project and must not be shared between multiple projects
#   * API_GATEWAY_ID
#   * API_GATEWAY_RESOURCE_ID

image: ${CI_IMAGE}

variables:
  CONTEXT: <context>
  SERVICE: <service>

stages:
  - staging
  - production

.serverless:
  only:
    - master
  except:
    - tags
  allow_failure: false    
  script:
    - npm install serverless-plugin-lambda-dead-letter --loglevel=error
    - vaultenv serverless deploy --stage ${ENVIRONMENT} --verbose

serverless:staging:
  stage: staging
  extends: .serverless 
  variables:
    ENVIRONMENT: staging

serverless:production:
  stage: production
  extends: .serverless
  when: manual  
  variables:
    ENVIRONMENT: production